name: 'Deploy AKS cluster using Bicep'

on:
  workflow_dispatch:

env:
  ResourceGroup: rg-gitops-demo
  Location: australiaeast
  ClusterName: clu-gitops
  RegistryName: GHCR
  RegistryServer: ghcr.io
  Namespace: apps-dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Azure login' 
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Create resource group'
        run: |
          az group create -l ${{ env.Location }} -n ${{ env.ResourceGroup }}

      # Create the AKS cluster
      
      - name: 'Run AKS deployment'
        run: |
          az deployment group create --name devenvironment --resource-group ${{ env.ResourceGroup }} --template-file ./infrastructure/aks/main.bicep --parameters ./infrastructure/aks/main.parameters.dev.json

      # Bootstrap Argo CD on the AKS cluster

      - name: 'Set the target AKS cluster'
        uses: Azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ env.ResourceGroup }}
          cluster-name: ${{ env.ClusterName }}

      - name: 'Create argocd namespace if not exist'
        run: |
          kubectl create namespace argocd --dry-run -o json | kubectl apply -f -  

      - name: 'Install Argo CD'
        run: |
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
      
      # Configure Argo CD App of Apps

      - name: 'Create the Dev Project'
        run: |
          kubectl apply -f argocd/projects/project-dev.yml       
          
      - name: 'Create Dev namespace if not exist'
        run: |
          kubectl create namespace ${{ env.Namespace }} --dry-run -o json | kubectl apply -f - 

      - name: 'Create imagepullsecret for the Registry'
        uses: azure/k8s-create-secret@v1
        with:
          container-registry-url: ${{ env.RegistryServer }}
          container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          secret-name: ${{ env.RegistryName }}-secret
          namespace: ${{ env.Namespace }}

      - name: 'Create the Root App'
        run: |
          kubectl apply -f argocd/apps-dev.yml
