name: 'Deploy AKS cluster'

on:
  workflow_dispatch:

env:
  ResourceGroup: rg-gitops-demo
  Location: australiaeast

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Azure login' 
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Create resource group'
        run: |
          az group create -l ${{ env.Location }} -n ${{ env.ResourceGroup }}

      - name: 'Create AKS resources from ARM template'
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.ResourceGroup }}
          template: ./infrastructure/aks/azuredeploy.json
          parameters: ./infrastructure/aks/azuredeploy.parameters.json