name: 'Bootstrap Argo CD on the AKS cluster'

on:
  workflow_dispatch:

env:
  ResourceGroup: rg-gitops-demo
  ClusterName: clu-gitops

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Azure login' 
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Set the target AKS cluster'
        uses: Azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: ${{ env.ResourceGroup }}
          cluster-name: ${{ env.ClusterName }}

      - name: 'Create argocd namespace if not exist'
        run: |
          kubectl create namespace argocd --dry-run -o json | kubectl apply -f -  

      - name: 'Install Argo CD'
        run: |
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml