apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
 name: dotnet-api-template
spec:
 generators:
 - git:
     repoURL: https://github.com/fabianmagrini/azure-gitops-demo.git
     revision: HEAD
     files:
     - path: "argocd/applicationset/cluster-config/**/config.json"
 template:
   metadata:
     name: 'dotnet-api-template-{{cluster.name}}'
   spec:
     project: appbundle-project-dev
     source:
       path: charts/template-api
       repoURL: https://github.com/fabianmagrini/dotnet-api-template.git
       targetRevision: HEAD
     destination:
       server: https://kubernetes.default.svc
       namespace: apps-dev