
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: appbundle-project-dev
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: The app bundle POC project

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'

  # Permit applications to deploy to any namespace in the same cluster
  destinations:
  - namespace: '*'
    server: '*'

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'